{% set name = "ckan" %}
{% set version = "2.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ckan-{{ version }}.tar.gz
  sha256: 6f7c67b2cc378d2935328d3d599dd22bda4115095e39c643898854b4563978a7

build:
  number: 0
  noarch: python
  entry_points:
    - ckan = ckan.cli.cli:ckan
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ez_setup
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - click

test:
  imports:
    - ckan
    - ckan.cli
  commands:
    - pip check
    - ckan --help
  requires:
    - pip

about:
  home: http://ckan.org/
  summary: CKAN Software for making open data websites.
  doc_url: https://docs.ckan.org/en/2.9/
  dev_url: https://github.com/ckan/ckan
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - mwilson8
    - benhuff
    - oblute
    - ndmaxar
