{% set name = "ckan" %}
{% set version = "2.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f7c67b2cc378d2935328d3d599dd22bda4115095e39c643898854b4563978a7

build:
  number: 0
  entry_points:
    - ckan = ckan.cli.cli:ckan
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - alembic ==1.7.5
    - babel ==2.9.0
    - beaker ==1.11.0
    - beautifulsoup4 ==4.10.0
    - bleach ==3.3.0
    - click ==7.1.2
    - cookiecutter ==1.7.3
    - decorator ==5.0.6
    - dominate ==2.6.0
    - fanstatic ==1.1
    - feedgen ==0.9.0
    - flask ==1.1.2
    - flask-multistatic ==1.0
    - flask-babel ==2.0.0
    - freezegun ==1.1.0
    - jinja2 ==2.11.3
    - markdown <=3.4.0
    - markupsafe ==1.1.1
    - passlib ==1.7.4
    - pastescript ==3.2.1
    - polib ==1.1.1
    - pycodestyle ==2.6.0
    - pyjwt ==2.3.0
    - pysolr ==3.9.0
    - pytest ==6.2.3
    - python-dateutil ==2.8.2
    - python-magic ==0.4.24
    - pytz ==2021.1
    - pyutilib ==6.0.0
    - pyyaml ==6.0
    - requests ==2.25.1
    - routes ==2.5.1
    - rq <=1.10.0
    - simplejson <=3.20.0
    - six ==1.15.0
    - sqlalchemy ==1.3.5 
    - tzlocal <4.0
    - webassets ==2.0
    - webhelpers ==1.3
    - webob ==1.8.7
    - werkzeug ==1.0.1
    - zope.interface ==5.4.0

test:
  imports:
    - ckan
    - ckan.cli
    - ckan.config
    - ckan.config.middleware
    - ckan.controllers
    - ckan.i18n
    - ckan.include
    - ckan.lib
    - ckan.lib.dictization
    - ckan.lib.navl
    - ckan.lib.repoze_plugins
    - ckan.lib.search
    - ckan.logic
    - ckan.logic.action
    - ckan.logic.auth
    - ckan.migration
    - ckan.migration.versions
    - ckan.model
    - ckan.pastertemplates
    - ckan.plugins
    - ckan.tests
    - ckan.tests.cli
    - ckan.tests.config
    - ckan.tests.controllers
    - ckan.tests.i18n
    - ckan.tests.legacy
    - ckan.tests.legacy.functional
    - ckan.tests.legacy.functional.api
    - ckan.tests.legacy.functional.api.model
    - ckan.tests.legacy.lib
    - ckan.tests.legacy.logic
    - ckan.tests.legacy.models
    - ckan.tests.legacy.schema
    - ckan.tests.lib
    - ckan.tests.lib.dictization
    - ckan.tests.lib.navl
    - ckan.tests.lib.search
    - ckan.tests.logic
    - ckan.tests.logic.action
    - ckan.tests.logic.auth
    - ckan.tests.migration
    - ckan.tests.model
    - ckan.tests.plugins
    - ckan.tests.pytest_ckan
    - ckan.views
    - ckanext
    - ckanext.audioview
    - ckanext.audioview.tests
    - ckanext.chained_functions
    - ckanext.chained_functions.tests
    - ckanext.datapusher
    - ckanext.datapusher.logic
    - ckanext.datapusher.tests
    - ckanext.datastore
    - ckanext.datastore.backend
    - ckanext.datastore.logic
    - ckanext.datastore.tests
    - ckanext.datatablesview
    - ckanext.example_database_migrations
    - ckanext.example_flask_iblueprint
    - ckanext.example_flask_iblueprint.tests
    - ckanext.example_flask_streaming
    - ckanext.example_flask_streaming.tests
    - ckanext.example_iapitoken
    - ckanext.example_iapitoken.tests
    - ckanext.example_iauthenticator
    - ckanext.example_iauthfunctions
    - ckanext.example_iclick
    - ckanext.example_iconfigurer
    - ckanext.example_iconfigurer.tests
    - ckanext.example_idatasetform
    - ckanext.example_idatasetform.tests
    - ckanext.example_idatastorebackend
    - ckanext.example_idatastorebackend.test
    - ckanext.example_igroupform
    - ckanext.example_igroupform.tests
    - ckanext.example_ipermissionlabels
    - ckanext.example_ipermissionlabels.tests
    - ckanext.example_iresourcecontroller
    - ckanext.example_itemplatehelpers
    - ckanext.example_itranslation
    - ckanext.example_itranslation.tests
    - ckanext.example_iuploader
    - ckanext.example_iuploader.test
    - ckanext.example_ivalidators
    - ckanext.example_ivalidators.tests
    - ckanext.example_theme_docs
    - ckanext.example_theme_docs.custom_config_setting
    - ckanext.example_theme_docs.custom_emails
    - ckanext.example_theme_docs.v01_empty_extension
    - ckanext.example_theme_docs.v02_empty_template
    - ckanext.example_theme_docs.v03_jinja
    - ckanext.example_theme_docs.v04_ckan_extends
    - ckanext.example_theme_docs.v05_block
    - ckanext.example_theme_docs.v06_super
    - ckanext.example_theme_docs.v07_helper_function
    - ckanext.example_theme_docs.v08_custom_helper_function
    - ckanext.example_theme_docs.v09_snippet
    - ckanext.example_theme_docs.v10_custom_snippet
    - ckanext.example_theme_docs.v11_HTML_and_CSS
    - ckanext.example_theme_docs.v12_extra_public_dir
    - ckanext.example_theme_docs.v13_custom_css
    - ckanext.example_theme_docs.v14_more_custom_css
    - ckanext.example_theme_docs.v15_fanstatic
    - ckanext.example_theme_docs.v16_initialize_a_javascript_module
    - ckanext.example_theme_docs.v17_popover
    - ckanext.example_theme_docs.v18_snippet_api
    - ckanext.example_theme_docs.v19_01_error
    - ckanext.example_theme_docs.v19_02_error_handling
    - ckanext.example_theme_docs.v20_pubsub
    - ckanext.example_theme_docs.v21_custom_jquery_plugin
    - ckanext.example_theme_docs.v22_fanstatic_and_webassets
    - ckanext.expire_api_token
    - ckanext.expire_api_token.tests
    - ckanext.imageview
    - ckanext.imageview.tests
    - ckanext.multilingual
    - ckanext.reclineview
    - ckanext.reclineview.tests
    - ckanext.resourceproxy
    - ckanext.resourceproxy.tests
    - ckanext.stats
    - ckanext.stats.public
    - ckanext.stats.public.ckanext
    - ckanext.stats.public.ckanext.stats
    - ckanext.stats.tests
    - ckanext.textview
    - ckanext.textview.tests
    - ckanext.videoview
    - ckanext.videoview.tests
    - ckanext.webpageview
    - ckanext.webpageview.tests
  commands:
    - ckan --help

about:
  home: http://ckan.org/
  license: GNU Affero General Public v3 or later (AGPLv3+)
  license_family: AGPL
  license_file: LICENSE.txt
  summary: CKAN Software for making open data websites.
  doc_url: https://docs.ckan.org/en/2.8/
  dev_url: https://github.com/ckan/ckan

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
