{% set name = "ckan" %}
{% set version = "2.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ckan/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: 6f7c67b2cc378d2935328d3d599dd22bda4115095e39c643898854b4563978a7
  patches:
    - webob.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - alembic ==1.0.0
    - babel ==2.7.0
    - beaker==1.11.0
    - bleach ==3.1.4
    - certifi ==2021.5.30
    - chardet ==4.0.0
    - click ==7.1.2 
    - dominate ==2.4.0
    - fanstatic >=1.1
    - feedgen ==0.9.0 
    - flask ==1.1.1
    - flask-babel ==1.0.0
    - flask-multistatic ==1.0 
    - flask ==1.1.1              
    - funcsigs ==1.0.2       
    - idna ==2.10
    - itsdangerous ==1.1.0
    - jinja2 ==2.10.1
    - lxml ==4.6.3
    - mako ==1.1.5     
    - markdown ==2.6.7
    - markupsafe ==1.1.1
    - nose ==1.3.7
    - passlib >=1.6.5
    - polib ==1.0.7
    - psycopg2 ==2.8.2
    - pyjwt==1.7.1 
    - python-magic ==0.4.15
    - pysolr ==3.6.0
    - python-dateutil ==2.8.2
    - python-editor==1.0.4 
    - pytz ==2016.7
    - pyutilib ==5.7.1
    - pyyaml ==5.4.1
    - redis ==3.5.3
    - repoze.lru ==0.7
    - repoze.who ==2.3
    - requests ==2.25.1
    - routes ==1.13
    - rq ==1.0
    - shutilwhich ==1.1.0
    - simplejson >=3.10.0
    - six ==1.16.0
    - sqlalchemy-migrate ==0.12.0
    - sqlalchemy ==1.3.5
    - sqlparse ==0.2.2
    - tzlocal ==1.3
    - unicodecsv ==0.14.1
    - urllib3==1.26.6
    - watchdog==2.1.5
    - webassets ==0.12.1
    - webencodings ==0.5.1 
    - webob ==1.8.7
    - werkzeug ==1.0.0
    - zope.interface >=4.3.2

test:
  imports:
    - ckan
    - ckan.plugins

  commands:
    - paster --version
    - paster --plugin=ckan --help

about:
  home: http://ckan.org/
  license: GNU Affero General Public v3 or later (AGPLv3+)
  license_family: AGPL
  license_file: LICENSE.txt
  summary: CKAN Software for making open data websites.
  doc_url: https://docs.ckan.org/en/2.8/
  dev_url: https://github.com/ckan/ckan

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - mwilson8
    - benhuff
    - oblute
    - ndmaxar
