{% set name = "ckan" %}
{% set version = "2.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ckan-{{ version }}.tar.gz
  sha256: 6f7c67b2cc378d2935328d3d599dd22bda4115095e39c643898854b4563978a7

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [win]

requirements:
  host:
    - ez_setup
    - pip
    - python
    - setuptools

  run:
    - python
    - alembic ==1.7.5
    - babel ==2.9.0
    - beaker ==1.11.0
    - beautifulsoup4 ==4.10.0
    - bleach ==3.3.0
    - click ==7.1.2
    - cookiecutter ==1.7.3
    - decorator ==5.0.6
    - dominate ==2.6.0
    - fanstatic ==1.1
    - feedgen ==0.9.0
    - flask ==1.1.2
    - flask-babel ==2.0.0
    - flask-multistatic
    - freezegun ==1.1.0
    - jinja2 ==2.11.3
    - markdown <=3.4.0
    - markupsafe ==1.1.1
    - passlib ==1.7.4
    - pastescript ==3.2.1
    - polib ==1.1.1
    - pycodestyle ==2.6.0
    - pyjwt ==2.3.0
    - pysolr ==3.9.0
    - pytest ==6.2.3
    - python-dateutil ==2.8.2
    - python-magic ==0.4.24
    - pytz ==2021.1
    - pyutilib ==6.0.0
    - pyyaml ==6.0
    - repoze.who ==2.4
    - requests ==2.25.1
    - routes ==2.5.1
    - rq <=1.10.0
    - simplejson <=3.20.0
    - six ==1.15.0
    - sqlalchemy <1.4
    - tzlocal <4.0
    - webassets ==2.0
    - webhelpers ==1.3
    - webob ==1.8.7
    - werkzeug ==1.0.1
    - zope.interface ==5.4.0

        
test:
  imports:
    - ckan
    - ckan.cli
  commands:
    - pip check
    - ckan --help
  requires:
    - pip


about:
  home: http://ckan.org/
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE.txt
  summary: CKAN Software for making open data websites.
  doc_url: https://docs.ckan.org/en/2.9/
  dev_url: https://github.com/ckan/ckan

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - mwilson8
    - benhuff
    - oblute
    - ndmaxar
